### ISSUE TITLE
vscode/other text editor theme?

### ISSUE THREAD

**Issue by dvanic** [DesiQuintans/pebbleslice-theme#2]
Hey! First, I wanted to say I absolutely LOVE these themes - it's what I've been looking for for teaching - and for work!

I was wondering - do you have any plans to port these to other editors (I'm especially interested in VSCode)?

**Comment by DesiQuintans** [comment]
Hello, thank you! I don't use any other editors so I have no plants to port the themes to anything else, but others are of course welcome to fork the themes and port them as needed.
